### ISSUE TITLE
تغیر اکانت وارپ به وارپ پلاس 

### ISSUE THREAD

**Issue by pr381s** [hamid-gh98/x-ui-scripts#1]
سلام دوست عزیز وقت بخیر
مایی که به صورت مستقیم پنل سنایی رو نصب نکردیم و غیرمستقیم نصب کردیم و دسترسی به منوی تنظیمات سنایی نداریم اومدیم برای نصب وارپ اسکریپت شما رو نصب کردیم و خوشبختانه موفق به نصب اسکریپت و فعالسازی وارپ شدیم اما حالا که کامند warp رو تایپ می‌کنیم حدود 14 گزینه برای ما میاره اما هیچ گزینه‌ای برای تغیر اکانت وارپ از وارپ عادی به وارپ پلاس وجود نداره 
در این منو با گزینه شماره 8 زیاد کار کردم اما مرتبط با نیاز بنده نبود و به مشابه منوی warp که در کناری پنل سنایی هست نبود که فقط نیاز بود کلید لایسنس وارپ پلاس مون رو وارد کنیم.
ممنون می‌شم در این رابط راهنمایی بفرمایید.
[تصویر 1](https://ibb.co/tQ6033V)

**Comment by hamid-gh98** [comment]
درود، ممنونم.
بله درسته، در پنل سنایی هم از همین اسکریپت استفاده میشه.
برای تبدیل اکانت میتونین از کامند `warp a` استفاده کنید.
