### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by l3lack-eyes** [hamid-gh98/x-ui-scripts#11]
خسته نباشید .
آپدیت جدید رو نصب کردم . کد json جدید هم جایگذاری کردم اما کار نمیکنه و ترافیک از دامین های warp شده رد نمیشه

**Comment by hamid-gh98** [comment]
درود، لطفا ابتدا
```sh
warp u
```
استفاده کنید و دوباره نصب کنید.

**Comment by l3lack-eyes** [comment]
خسته نباشید . درست شده ولی بعد 10 دقیقه از کار میافته آیپی سرور خودم مبشه
