### ISSUE TITLE
The option Change to WARP+ account (warp a) does not work in version 3.03

### ISSUE THREAD

**Issue by MolodoGvardeets** [hamid-gh98/x-ui-scripts#14]
Now I can't enter the WARP+ license. After entering the license, the following message appears

**License should be 26 characters, please re-enter WARP+ License. Otherwise press Enter to continue. (4 times remaining):**

![2024-03-21_11-50-26](https://github.com/hamid-gh98/x-ui-scripts/assets/26322490/86437176-93c7-497a-bec7-9d1e551fb11c)

**Comment by hamid-gh98** [comment]
Hello, this script is using another script to install the warp, and there is nothing for us to do with it.

HINT: *Please ensure remove any space or other character from before and after licence key.*
