### ISSUE TITLE
غیر فعال کردن IP6

### ISSUE THREAD

**Issue by straymail** [hamid-gh98/x-ui-scripts#2]
سلام قربان

وقت شما بخیر

امکانش هست نحوه غیر فعال کردن IP6 این اسکریپت رو بفرمایید

با سپاس

**Comment by straymail** [comment]
درود

ما اون اسکریپتی که برای پنل 3x-ui پیشنهاد شده داخل پیجشون نصب میکنیم

یک آی پی 4 میده یک 6
با اینکه سرور من بصورت پیشفرض آِ پی 6 نداره، این آی پی 6 باعث شده گوگل مرتب کپچا بخواد

**Comment by hamid-gh98** [comment]
[این رو ببینید](https://github.com/hamid-gh98/x-ui-scripts#notes)
