### ISSUE TITLE
Your Warp script gives Errors during installation.

### ISSUE THREAD

**Issue by Enkidu-6** [hamid-gh98/x-ui-scripts#3]
Hi and thanks for the nice work.

fscarmen's Warp repo has been disabled by github. 

https://github.com/fscarmen/warp

Since your script pulls data from that repository, it chokes in the middle of the installation.  Although fscarmen claims to be back in two days, (I'm assuming he/she is trying to remove some codes to comply with github policies) I hope you have a fork or clone of that repository somewhere in case the main Repo never comes back. 

I also hope there's no automatic update set up anywhere in your script or in 3x-ui because that will most likely break everyone's installation.

Cheers.

**Comment by deathline94** [comment]
same problem . 
'  [ERROR] Sorry, the installation of WARP socks5 proxy (WireProxy) failed! Please try again later.'
as the OP says its due to a problem resulting in the og repo getting suspended

**Comment by Enkidu-6** [comment]
They've moved their Repository from github to gitlab. You may want to update your scripts.

https://gitlab.com/fscarmen/warp

**Comment by hamid-gh98** [comment]
Thank u for informing me.
