### ISSUE TITLE
error during warp wireproxy installation

### ISSUE THREAD

**Issue by niiaco** [hamid-gh98/x-ui-scripts#6]
im experiencing this error all the time
 [ERROR] Sorry, the reinstallation of WARP socks5 proxy (WireProxy) failed! Please try again later.

**Comment by hamid-gh98** [comment]
Hello, the error occurred due to the recent update of the fscarmen/warp script to version 3.0.0.
I had used a different version of the script previously. please test it now.

**Comment by bmv2020** [comment]
> Hello, the error occurred due to the recent update of the fscarmen/warp script to version 3.0.0. I had used a different version of the script previously. please test it now.

Its not working.

it say:

[ERROR] The WARP socks5 proxy (WireProxy) failed to start! Please try again later.

**Comment by niiaco** [comment]
All dependencies already exist and do not need to be installed additionally. 

 Checking VPS infomation... 
 Cannot find the account file: /etc/wireguard/warp-account.conf, you can reinstall with the WARP+ License
