### ISSUE TITLE
  [ERROR] Sorry, the installation of WARP socks5 proxy (WireProxy) failed! Please try again later.   

### ISSUE THREAD

**Issue by l3lack-eyes** [hamid-gh98/x-ui-scripts#7]
روزتون بخیر . دلیلش چیه؟

**Comment by mobagheri** [comment]
با سلام. منم دارم همش همین ارور رو میگیرم.. دلیلش چی هست؟

**Comment by l3lack-eyes** [comment]
@akajaber
راهکار چیه دوست عزیز ؟

**Comment by mobagheri** [comment]
فعلا از اسکریپت چینی استفاده کنید تا مشکل این اسکریپت برطرف بشه... نصب کردم این اسکریپت رو و اکی هست.

bash <(wget -qO- https://gitlab.com/rwkgyg/CFwarp/raw/main/CFwarp.sh 2> /dev/null)

ابتدا گزینه 2 و کمی صبر میکنیم. در مرحله بعد باز هم گزینه 2 و باز هم صبر می کنیم. در انتها هم گزینه 0 و تمام.

**Comment by hamid-gh98** [comment]
Hello, the error occurred due to the recent update of the fscarmen/warp script to version 3.0.0.
I had used a different version of the script previously. please test it now.

**Comment by l3lack-eyes** [comment]
خسته نباشید
پنل علیرضا دارم اجازه نصب وارپ نمیده راهکار چیه؟
