### ISSUE TITLE
[ERROR] Sorry, the reinstallation of WARP socks5 proxy (WireProxy) failed! Please try again later.

### ISSUE THREAD

**Issue by akajaber** [hamid-gh98/x-ui-scripts#8]
درود
با توجه به اینکه در 24 ساعت گذشته مخازن مرتبط با اسکریپت در گیت‌هاب غیرفعال شدند، با وجود اینکه فراخوانی warp از گیت لب در اسکریپت انجام شده اما اسکریپت fscarmen هم گویا به آپدیت نیاز داره و هنوز اقدامی نکرده.

[Ln: 479](https://github.com/hamid-gh98/x-ui-scripts/blob/8783233d23dd470b25fa71868852bf464f4da354/install_warp_proxy.sh#L479C31-L479C82)

مواردی که توسط گیتهاب دیزیبل شدن : 
[PLUS acc type](https://github.com/aliilapro/warp-plus-cloudflare.git)
[Resolver](https://github.com/fscarmen/warp/releases/download/resolvconf/resolvconf)
و در اسکریپت اصلی fscarmen هنوز آدرس دهی به Github هست.
همینطور api وایرگارد در آدرس : 

`fscarmen.cloudflare.now.cc/wg`
و 
`wg.cloudflare.now.cc`

همگی غیرفعال هستند.

**در اصل مشکل از کد شما نیست و برای شفافیت دوستان دیگر ذکر شد.**

**Comment by mobagheri** [comment]
فعلا از اسکریپت چینی استفاده کنید تا مشکل این اسکریپت برطرف بشه... نصب کردم این اسکریپت رو و اکی هست.

bash <(wget -qO- https://gitlab.com/rwkgyg/CFwarp/raw/main/CFwarp.sh 2> /dev/null)

ابتدا گزینه 2 و کمی صبر میکنیم. در مرحله بعد باز هم گزینه 2 و باز هم صبر می کنیم. در انتها هم گزینه 0 و تمام.

**Comment by Alireza78na** [comment]
> فعلا از اسکریپت چینی استفاده کنید تا مشکل این اسکریپت برطرف بشه... نصب کردم این اسکریپت را و اکی هست.
> 
> bash <(wget -qO- https://gitlab.com/rwkgyg/CFwarp/raw/main/CFwarp.sh 2> /dev/null)
> 
> جهت نصب پروکسی وارپ روی پورت 40000، بعد از اجرا کردن اسکریپت فوق در ترمینال کمی صبر می کنیم تا منوی آن ظاهر شود. سپس گزینه 2 را انتخاب کرده و صبر می کنیم تا مراحل اولیه نصب پیش رود. در مرحله بعد باز هم گزینه 2 را انتخاب کرده و صبر می کنیم تا پروکسی نصب شود. در انتها نیز گزینه 0 را انتخاب کرده و تمام.
> 
> جهت دسترسی به گیت هاب این اسکریپت هم از آدرس زیر استفاده کنید:
> 
> https://github.com/yonggekkk/warp-yg
این اسکریپت فایل وایرگارد warp رو کجا ذخیره میکنه؟

**Comment by hamid-gh98** [comment]
> درود
> با توجه به اینکه در 24 ساعت گذشته مخازن مرتبط با اسکریپت در گیت‌هاب غیرفعال شدند، با وجود اینکه فراخوانی warp از گیت لب در اسکریپت انجام شده اما اسکریپت fscarmen هم گویا به آپدیت نیاز داره و هنوز اقدامی نکرده.
> 
> [Ln: 479](https://github.com/hamid-gh98/x-ui-scripts/blob/8783233d23dd470b25fa71868852bf464f4da354/install_warp_proxy.sh#L479C31-L479C82)
> 
> مواردی که توسط گیتهاب دیزیبل شدن : 
> [PLUS acc type](https://github.com/aliilapro/warp-plus-cloudflare.git)
> [Resolver](https://github.com/fscarmen/warp/releases/download/resolvconf/resolvconf)
> و در اسکریپت اصلی fscarmen هنوز آدرس دهی به Github هست.
> همینطور api وایرگارد در آدرس : 
> 
> `fscarmen.cloudflare.now.cc/wg`
> و 
> `wg.cloudflare.now.cc`
> 
> همگی غیرفعال هستند.
> 
> **در اصل مشکل از کد شما نیست و برای شفافیت دوستان دیگر ذکر شد.**
> 

درود، ممنون از توضیحات شما.
