### ISSUE TITLE
[ERROR] The WARP socks5 proxy (WireProxy) failed to start! Please try again later.   

### ISSUE THREAD

**Issue by iarmawn** [hamid-gh98/x-ui-scripts#9]
When I try to use the script, the installation seems to work fine but then i get this error and nothing else.
Please enter a port for WireProxy (1-65535): 
  >  WireProxy [Default '40000'] (Remaining attempts: 5):
  Completed! WARP socks5 proxy (WireProxy) has been reinstalled and is ready to use. 
  WARP is listening on socks5://127.0.0.1:
                                                      
  [ERROR] The WARP socks5 proxy (WireProxy) failed to start! Please try again later.

**Comment by bmv2020** [comment]
من هم این خطا رو دارم
I have the same issue.

**Comment by SirAmirss** [comment]
مشکل در قسمت قرار دادن ورژن 2.5.3 هست که به اشتباه ورژن beta 3.0.0 نصب میشه که این نسخه مشکل بالا رو داره ، برای حل این مشکل کد رو فورک کنید و فایل install_warp_proxy.sh رو ادیت کنید ، دنبال بخشی که نوشته 
    # Temporary fix for error during installation after version 3.0.0 fscarmen/warp !!
    # Using the version 2.5.3 for now until it get fixed!
    # wget -N -P /etc/wireguard https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh
    بگرد و  اول دستور زیر رو پاک کن
    
     wget -N -P /etc/wireguard https://gitlab.com/fscarmen/warp/-/raw/594e1d5944ce357ea865054fa53ed4c050ec3c49/menu.sh
     
     بعد # پشت دستور 
     wget -N -P /etc/wireguard https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh
      رو پاک کن 
      
      که به صورت زیر بشه
 # Temporary fix for error during installation after version 3.0.0 fscarmen/warp !!
 # Using the version 2.5.3 for now until it get fixed!
   wget -N -P /etc/wireguard https://gitlab.com/fscarmen/warp/-/raw/main/menu.sh
   
   سیو کن و با ایدی گیت هاب خودت نصبش کن 
   یا میتونی از فورک من استفاده کنی این کار هارو انجام دادم:
   
   bash <(curl -sSL https://raw.githubusercontent.com/SirAmirss/x-ui-scripts/main/install_warp_proxy.sh)
